### ISSUE TITLE
Telescope installation 

### ISSUE THREAD

**Issue by GislaineCurty** [mlbendall/telescope#1]
I'm trying to install the Telescope, but I have obtained an error message.
I'm using a virtual environment in the server, anaconda2, to install the packeges. I installed all packeges required by telescope (numpy (>=1.13), scipy (>=0.19.0), intervaltree, and pysam (>=0.12)). 

The error message:

(/home/gcurty/projeto/bin/telescope) [gcurty@crab telescope]$ pip install git+git://github.com/mlbendall/telescope.git
Collecting git+git://github.com/mlbendall/telescope.git
  Cloning git://github.com/mlbendall/telescope.git to /tmp/pip-req-build-ij2v2ng0
    Complete output from command python setup.py egg_info:
    Compiling src/calignment.pyx because it changed.
    [1/1] Cythonizing src/calignment.pyx
    /home/gcurty/projeto/bin/telescope/lib/python3.6/site-packages/Cython/Compiler/Main.py:367: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-req-build-ij2v2ng0/src/calignment.pyx
      tree = Parsing.p_module(s, pxd, full_module_name)
   
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    __copyright__ = "Copyright (C) 2017 Matthew L. Bendall"
   
   
    cdef class AlignedPair:
   
        def __cinit__(self, AlignedSegment r1, AlignedSegment r2 = None):
                           ^
    ------------------------------------------------------------
   
    src/calignment.pyx:11:24: 'AlignedSegment' is not a type identifier
   
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    __copyright__ = "Copyright (C) 2017 Matthew L. Bendall"
   
   
    cdef class AlignedPair:
   
        def __cinit__(self, AlignedSegment r1, AlignedSegment r2 = None):
                                              ^
    ------------------------------------------------------------
   
    src/calignment.pyx:11:43: 'AlignedSegment' is not a type identifier
   
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
   
        def __dealloc__(self):
            del self.r1
            del self.r2
   
        cpdef int write(self, AlignmentFile outfile):
                             ^
    ------------------------------------------------------------
   
    src/calignment.pyx:19:26: 'AlignmentFile' is not a type identifier
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ij2v2ng0/setup.py", line 39, in <module>
        extensions = cythonize(extensions)
      File "/home/gcurty/projeto/bin/telescope/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1097, in cythonize
        cythonize_one(*args)
      File "/home/gcurty/projeto/bin/telescope/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1220, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: src/calignment.pyx

My Cython version is 0.29.1.

**Comment by mlbendall** [comment]
We have successfully used cython v0.28 and v0.29, so probably not the cython version. Our testing environment includes miniconda 3 (4.3.27.1) and python 3.6.

The following works with miniconda3:

```
conda create -n teletest python=3.6 numpy=1.13 scipy=0.19.0 pysam=0.12 cython intervaltree
conda activate teletest
pip install git+git://github.com/mlbendall/telescope.git
telescope assign -h
```

**Comment by GislaineCurty** [comment]
I was able to install now!

 Thank you so much!

**Comment by mlbendall** [comment]
Good luck!

**Comment by aasifstrikes** [comment]
When i run this code, "pip install git+git://github.com/mlbendall/telescope.git", I am getting the following error:

 fatal: unable to connect to github.com:
  github.com[0: 20.26.156.215]: errno=Connection timed out

WARNING: Discarding git+git://github.com/mlbendall/telescope.git. Command errored out with exit status 128: git clone --filter=blob:none -q git://github.com/mlbendall/telescope.git /tmp/pip-req-build-h_otqix3 Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone --filter=blob:none -q git://github.com/mlbendall/telescope.git /tmp/pip-req-build-h_otqix3 Check the logs for full command output.

How do i solve this?
