### ISSUE TITLE
KeyError: 'locus'

### ISSUE THREAD

**Issue by somethingp** [mlbendall/telescope#13]
I'm trying to run it with a GTF file from UCSC (repeats from repeatmasker), but I get the following output and error:
2020-03-16 19:26:58 INFO     
Version:                          1.0.3
Input Options
    samfile:                      SRR6355957Aligned.out.sam
    gtffile:                      ERVs.gtf
    attribute:                    locus
    no_feature_key:               __no_feature
    ncpu:                         1
    tempdir:                      None
Reporting Options
    quiet:                        False
    debug:                        False
    logfile:                      <stderr>
    outdir:                       .
    exp_tag:                      telescope
    updated_sam:                  False
Run Modes
    reassign_mode:                exclude
    conf_prob:                    0.9
    overlap_mode:                 threshold
    overlap_threshold:            0.2
    annotation_class:             intervaltree
Model Parameters
    pi_prior:                     0
    theta_prior:                  200000
    em_epsilon:                   1e-07
    max_iter:                     100
    use_likelihood:               False
    skip_em:                      False
 (from run in telescope_assign.py:197)
2020-03-16 19:26:58 INFO     Loading annotation...                                        (from run in telescope_assign.py:205)
Traceback (most recent call last):
  File "/home/prakharbansal/path/to/miniconda3/envs/telescope_env/bin/telescope", line 8, in <module>   
    sys.exit(main())
  File "/home/prakharbansal/path/to/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/__main__.py", line 95, in main
    args.func(args)
  File "/home/prakharbansal/path/to/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/telescope_assign.py", line 207, in run
    annot = Annotation(opts.gtffile, opts.attribute)
  File "/home/prakharbansal/path/to/miniconda3/envs/telescope_env/lib/python3.6/site-packages/telescope/utils/_annotation_intervaltree.py", line 41, in __init__
    if attr[self.key] not in self.loci:
KeyError: 'locus'

**Comment by shenmeguimlf** [comment]
Hi, I got the same error, how did you fix it?

**Comment by CWYuan08** [comment]
Hi, I also got the same error @somethingp @shenmeguimlf, did you manage fix it? Thanks!

**Comment by Kiliankleemann** [comment]
Same here

**Comment by AlisaGU** [comment]
@Kiliankleemann Hi, it may be the problem of the annotation's format.

An example of my raw annotation, and it failed.
```
chr1	RepeatMasker	Transposon	9	1239	6123	-	.	ID Denovo_TE00000001; Target rnd-6_family-1051 4089 5314; Class LTR/Gypsy; PercDiv 13.9; PercDel 4.4; PercIns 4.8;
```
After comparing with Telescope's example data, I added quote to each value in the 9th column. It succeeded!
```
chr1	RepeatMasker	Transposon	9	1239	6123	-	.	ID "Denovo_TE00000001"; Target "rnd-6_family-1051 4089 5314"; Class "LTR/Gypsy"; PercDiv "13.9"; PercDel "4.4"; PercIns "4.8";
```
