### ISSUE TITLE
How to run telescope on single cell dataset

### ISSUE THREAD

**Issue by zijzhang** [mlbendall/telescope#32]
I have one single-cell RNAseq dataset. When I run 'telescope sc assign [samfile] [gtffile]', there is an error
![image](https://user-images.githubusercontent.com/40446208/166089339-8d1a8561-8679-4f6c-97da-4a16cf5fbfac.png). 
It seems that the sc does not work

Information:
The system is Red Hat Enterprise Linux Server release 7.7(Maipo)
python=3..8.1
The telescope was installed by conda install -c bioconda telescope

**Comment by mlbendall** [comment]
We are currently working on STELLARscope, the single-cell version of Telescope. Stay tuned!
