### ISSUE TITLE
Telescope Bioconda Package

### ISSUE THREAD

**Issue by davebx** [mlbendall/telescope#6]
Good day,

I am working on a bioconda recipe for telescope, but the v1.0.2 tag is having trouble building with `conda build`, while the master branch builds and tests perfectly. Is the code at a place where you can predict when the 1.0.3 release will be out?

**Comment by mlbendall** [comment]
I've released 1.0.3. Installs fine using the method in the README but circleci build is 
failing. It seems like the pysam/htslib headers are needed for the build process. I've attached my current [meta.yaml.txt](https://github.com/mlbendall/telescope/files/3159097/meta.yaml.txt), maybe you have some insight about how to get this to work. Thanks!

**Comment by davebx** [comment]
@mlbendall Thanks, I've created a pull request for a bioconda recipe at bioconda/bioconda-recipes#15369. You'll notice that I included the DOI from your recipe, and the version pinnings in my meta.yaml seemed to do the trick for the rest.

**Comment by davebx** [comment]
Closing this since there's a wrapper available on the official toolshed and the conda package works.
